
app:
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/orderdb
    username: postgres
    password: password
    pool-size: 30


server:
  port: 8006
rootProject:
   name: 'orders-service'

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: order-service
  rabbitmq:
     host: localhost
     port: 15672
     username: guest
     password: guest
order:
   rabbitmq:
     exchange: servicesExchange
     routingkey: orders.*